# Generated by Django 6.0.4 on 2026-04-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('analyst', 'Analyst'), ('technician', 'Technician')], default='analyst', max_length=20),
        ),
    ]
