# Generated by Django 6.0.4 on 2026-04-23 16:03

from django.db import migrations


def normalize_employee_position(apps, schema_editor):
    Employee = apps.get_model("tickets", "Employee")

    for employee in Employee.objects.all():
        position = (employee.position or "").strip().lower()
        if position == "technician":
            employee.position = "technician"
        else:
            employee.position = "analyst"
        employee.save(update_fields=["position"])


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_employee_position"),
    ]

    operations = [
        migrations.RunPython(
            normalize_employee_position,
            migrations.RunPython.noop,
        ),
    ]
